version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=C0V1D19
      - POSTGRES_DB=microservice_admin_db
    ports:
      - "54320:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data/